### ISSUE TITLE
前端 我用另外一个  但是出错 用的是 express框架

### ISSUE THREAD

**Issue by talway** [keenwon/mongodb-to-elasticsearch#2]
UserSearchService
https://github.com/IdanFridman/UserSearchService

http://www.javacodegeeks.com/2014/08/my-exprience-using-elasticsearch-nodejs-and-expressjs.html?utm_source=tuicool

我使用这个 但是总是出错，

我是安装express

git clone https://github.com/IdanFridman/UserSearchService.git

安装依赖

执行命令；

出现以下错误

[root@talway UserSearchService]# npm install
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module

> websocket@1.0.8 install /root/UserSearchService/node_modules/websocket
> node install.js

[websocket v1.0.8] Attempting to compile native extensions.
[websocket v1.0.8] Native extension compilation successful!

> ws@0.4.31 install /root/UserSearchService/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/root/UserSearchService/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory`/root/UserSearchService/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
\

> ws@0.4.31 install /root/UserSearchService/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/root/UserSearchService/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory`/root/UserSearchService/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
debug@0.7.4 node_modules/debug

static-favicon@1.0.2 node_modules/static-favicon

morgan@1.0.1 node_modules/morgan
└── bytes@0.3.0

q@1.0.1 node_modules/q

cookie-parser@1.0.1 node_modules/cookie-parser
├── cookie-signature@1.0.3
└── cookie@0.1.0

elasticsearchclient@0.5.3 node_modules/elasticsearchclient

ejs@1.0.0 node_modules/ejs

body-parser@1.0.2 node_modules/body-parser
├── qs@0.6.6
├── raw-body@1.1.7 (string_decoder@0.10.31, bytes@1.0.0)
└── type-is@1.1.0 (mime@1.2.11)

express@4.2.0 node_modules/express
├── parseurl@1.0.1
├── utils-merge@1.0.0
├── cookie@0.1.2
├── escape-html@1.0.1
├── merge-descriptors@0.0.2
├── cookie-signature@1.0.3
├── debug@0.8.1
├── qs@0.6.6
├── range-parser@1.0.0
├── fresh@0.2.2
├── methods@1.0.0
├── buffer-crc32@0.2.1
├── serve-static@1.1.0
├── path-to-regexp@0.1.2
├── type-is@1.1.0 (mime@1.2.11)
├── accepts@1.0.1 (negotiator@0.4.9, mime@1.2.11)
└── send@0.3.0 (debug@0.8.0, mime@1.2.11)

websocket@1.0.8 node_modules/websocket

hjs@0.0.6 node_modules/hjs
└── hogan.js@3.0.2 (mkdirp@0.3.0, nopt@1.0.10)

jade@1.7.0 node_modules/jade
├── character-parser@1.2.0
├── commander@2.1.0
├── void-elements@1.0.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── with@3.0.1 (uglify-js@2.4.20)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
├── monocle@1.1.51 (readdirp@0.2.5)
└── constantinople@2.0.1 (uglify-js@2.4.20)

socket.io@1.0.6 node_modules/socket.io
├── has-binary-data@0.1.1 (isarray@0.0.1)
├── socket.io-parser@2.2.0 (isarray@0.0.1, emitter@1.0.1, json3@3.2.6)
├── socket.io-adapter@0.2.0 (socket.io-parser@2.1.2)
├── engine.io@1.3.1 (base64id@0.1.0, debug@0.6.0, engine.io-parser@1.0.6, ws@0.4.31)
└── socket.io-client@1.0.6 (indexof@0.0.1, to-array@0.1.3, component-bind@1.0.0, object-component@0.0.3, component-emitter@1.1.2, parseuri@0.0.2, engine.io-client@1.3.1)

less-middleware@1.0.4 node_modules/less-middleware
├── mkdirp@0.3.5
├── node.extend@1.0.10 (is@0.3.0)
└── less@1.7.5 (graceful-fs@3.0.6, mime@1.2.11, mkdirp@0.5.0, clean-css@2.2.23, source-map@0.1.43, request@2.40.0)
[root@talway UserSearchService]# ls
README.md  bin         controllers   package.json  routes    tasks
app.js     bower.json  node_modules  public        services
[root@talway UserSearchService]# node app.js
[root@talway UserSearchService]#

**Comment by keenwon** [comment]
express的问题看 https://github.com/strongloop/express
